# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Alergia')),
            ],
        ),
        migrations.AlterField(
            model_name='bombero',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado/a'), ('Soltero', 'Soltero/a'), ('Divorciado', 'Divorciado/a'), ('Viudo', 'Viudo/a'), ('Concubino', 'Concubino/a')], default='Casado', max_length=255, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='direccionelectronica',
            name='uso',
            field=models.CharField(choices=[('P', 'Particular'), ('L', 'Laboral')], default='P', max_length=255, verbose_name='Uso'),
        ),
        migrations.AlterField(
            model_name='direccionpostal',
            name='uso',
            field=models.CharField(choices=[('P', 'Particular'), ('L', 'Laboral')], default='P', max_length=255, verbose_name='Uso'),
        ),
        migrations.AlterField(
            model_name='direccionweb',
            name='tipo',
            field=models.CharField(choices=[('S', 'Perfil Web Social'), ('L', 'Pagina Web Laboral')], default='S', max_length=255, verbose_name='Tipo web'),
        ),
        migrations.AlterField(
            model_name='direccionweb',
            name='uso',
            field=models.CharField(choices=[('P', 'Particular'), ('L', 'Laboral')], default='P', max_length=255, verbose_name='Uso'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='parentesco',
            field=models.CharField(choices=[('Hermano', 'Hermano/a'), ('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo/a'), ('Abuelo', 'Abuelo/a'), ('Nieto', 'Nieto/a'), ('Tio', 'Tío/a'), ('Primo', 'Primo/a'), ('Esposo', 'Esposo/a')], default='Hermano', max_length=255, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='factor_sanguineo',
            field=models.CharField(choices=[('+', 'RH+'), ('-', 'RH-')], default='+', max_length=255, verbose_name='Factor Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('AB', 'Grupo AB'), ('A', 'Grupo A'), ('B', 'Grupo B'), ('O', 'Grupo O')], default='AB', max_length=255, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE')], default='DNI', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(choices=[('C', 'Celular'), ('F', 'Fijo')], default='C', max_length=255, verbose_name='Tipo de Teléfono'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='uso',
            field=models.CharField(choices=[('P', 'Particular'), ('L', 'Laboral')], default='P', max_length=255, verbose_name='Uso'),
        ),
    ]
